# Rotas relacionadas ao MQTT
- from:
    uri: rest:post:/test-mqtt
    steps:
      - log:
          message: "Testing MQTT WebSocket... Body: ${body}"
      - doTry:
          steps:
            - to:
                uri: paho-mqtt5:test?lazyStartProducer=true
            - setBody:
                constant: '{"status": "mqtt_sent", "message": "Sent to MQTT via WebSocket"}'
          doCatch:
            - exception:
                - java.lang.Exception
              steps:
                - log:
                    message: "MQTT WebSocket connection failed: ${exception.message}"
                - setBody:
                    constant: '{"status": "mqtt_failed", "message": "MQTT WebSocket broker not available"}'
          doFinally:
            steps:
              - setHeader:
                  name: Content-Type
                  constant: application/json
